feat: add resize option
eslint/playground pull request #59
Opened 2022-05-29 08:39 UTC by amareshsm

**Description:**

Added resizable split-view to the playground to resize editor and msg pane.

Ref: #28 

https://user-images.githubusercontent.com/30730124/170859446-8148e471-651c-45b8-ac27-888cbcf4dc75.mov

2022-05-29 08:40 UTC, amareshsm commented
#28

2022-05-29 09:32 UTC, snitin315 approved these changes
This looks good. Thank you for contributing.

Would like a review from @nzakas as well.

2022-06-01 21:44 UTC, nzakas requested changes
This looks really nice! Can you also remove `resize: vertical` from the style for that pane?

2022-06-02 05:13 UTC, harish-sethuraman commented on src/playground/scss/split-pane.scss
> +    background-color: var(--divider-color);
Remove the one that isn't needed?

2022-06-02 18:25 UTC, amareshsm commented on src/playground/scss/split-pane.scss
> +    background-color: var(--divider-color);
sure  👍

2022-06-02 20:45 UTC, nzakas approved these changes
LGTM. Thanks so much!

2022-06-02 20:45 UTC, merged